import MosqueIcon from '@mui/icons-material/Mosque';
import VolunteerActivismIcon from '@mui/icons-material/VolunteerActivism';
import SchoolIcon from '@mui/icons-material/School';
import BusinessIcon from '@mui/icons-material/Business';

export const DEFAULT_SITE_TYPE = 'beit-knesset';

export const SITE_TYPES = {
  'beit-knesset': {
    id: 'beit-knesset',
    label: 'בית כנסת',
    pluralLabel: 'בתי כנסת',
    Icon: MosqueIcon,
    namePrefix: 'בית כנסת',
    nameFieldLabel: 'שם בית הכנסת *',
    namePlaceholder: 'לדוגמה: שערי תפילה',
    slugPlaceholder: 'beit-knesset/shaarei-tefila',
    aboutLabel: 'כמה מילים על בית הכנסת',
    aboutPlaceholder: 'ספרו בקצרה על הקהילה, האווירה והייחוד של המקום',
    heroTitle: 'צור אתר לבית הכנסת שלך',
    registerTitle: 'צור אתר לבית הכנסת שלך',
    ctaDescription: 'תפילות, הודעות, תשלומים, גלריה וניהול קהילה באתר אחד.',
    defaultSubtitle: 'קהילה, תפילה וחסד',
    defaultName: 'בית כנסת',
    pages: {
      schedule: {
        title: 'זמני תפילות ושיעורים',
        emptyText: 'לא הוזנו זמני תפילות עדיין',
        adminTitle: 'זמני תפילות',
        sectionPlaceholder: 'לדוגמה: ימי חול / שבת קודש / שיעורים',
        rowLabel: 'שם התפילה או השיעור',
        rowPlaceholder: 'לדוגמה: שחרית',
        saveLabel: 'שמור זמנים',
        savedMessage: 'זמני התפילות עודכנו בהצלחה',
        pdfTitle: 'זמני תפילות ושיעורים',
      },
      announcements: {
        title: 'הודעות',
        emptyText: 'אין הודעות כרגע',
        addTitle: 'הוסף הודעה חדשה',
        activeTitle: 'הודעות פעילות',
        publishLabel: 'פרסם הודעה',
        pinnedLabel: 'הצמד הודעה לראש הרשימה',
      },
      content: {
        title: 'קניית ברכות',
        subtitle: 'זכו בברכה בציבור לעצמכם ולאהוביכם',
        description: 'לרכישת ברכה — בחרו ברכה מהרשימה, שלמו בכל אמצעי התשלום הנוח לכם ואשרו לגבאות',
        adminTitle: 'הוספה ועריכה של ברכות',
        activeTitle: 'ברכות פעילות',
        itemNameLabel: 'שם הברכה',
        itemDescriptionLabel: 'תיאור',
        addLabel: 'הוסף ברכה',
        saveLabel: 'שמור ברכה',
        specialCtaTitle: 'רוצים ברכה מיוחדת שלא ברשימה?',
        specialCtaText: 'פנו ישירות לגבאות ונשמח להתאים ברכה לכל אירוע ומועד',
      },
      payments: {
        title: 'תשלומים',
        subtitle: 'בחרו את האמצעי הנוח לכם',
        bankDescription: 'העברה ישירה לחשבון בית הכנסת',
        standingOrderDescription: 'הגדירו תשלום חודשי קבוע לתמיכה שוטפת',
        accountCtaTitle: 'רוצים לראות את החשבון שלכם?',
        accountCtaText: 'התחברו עם Google ובדקו כמה אתם חייבים לבית הכנסת',
        accountButton: 'לחשבון האישי שלי',
        standingOrderNote: 'יש למלא ולהחזיר לגבאות',
      },
      campaigns: {
        title: 'קמפיינים',
        subtitle: 'קמפיין התרמה עם יעד, מתרימים ולינקים אישיים',
        emptyText: 'אין קמפיינים פעילים כרגע',
        donateLabel: 'תרומה לקמפיין',
        shareLabel: 'שיתוף קישור',
        raiserTitle: 'מתרימים',
        raisedLabel: 'נאסף',
        goalLabel: 'יעד',
        matchedLabel: 'לאחר הכפלה',
      },
      contact: {
        subtitle: 'אנחנו כאן לכל שאלה ובקשה',
        formTitle: 'שלחו הודעה',
        mapTitle: 'מפת בית הכנסת',
        whatsappTitle: 'הצטרפו לקבוצת הוואטסאפ',
        whatsappText: 'קבלו עדכונים, הודעות ושיעורי תורה ישירות לנייד',
        subjects: ['שאלה כללית', 'תשלום / חשבון', 'עלייה לתורה', 'שיעורי תורה', 'אירוע / שמחה', 'אחר'],
      },
      admin: {
        loginSubtitle: 'גבאות',
        settings: 'פרטי האתר',
        schedule: 'זמני תפילות',
        charges: 'חיובי מתפללים',
      },
    },
    nav: [
      { label: 'ראשי', path: '' },
      { label: 'זמנים', path: 'zmanim' },
      { label: 'הודעות', path: 'hodaot' },
      { label: 'ברכות', path: 'brachot' },
      { label: 'תשלומים', path: 'tashlumim' },
      { label: 'קמפיינים', path: 'campaigns' },
      { label: 'גלריה', path: 'galeria' },
      { label: 'יצירת קשר', path: 'contact' },
      { label: 'ניהול', path: 'admin', adminLink: true },
    ],
    ticker: [
      { cat: 'לרפואה שלמה', text: 'לרפואת משה בן שרה' },
      { cat: 'לעילוי נשמת', text: 'לעילוי נשמת יעקב בן רחל' },
      { cat: 'להצלחה', text: 'להצלחת כל התורמים והמתפללים' },
    ],
    templateName: 'בית כנסת',
  },
  amuta: {
    id: 'amuta',
    label: 'עמותה',
    pluralLabel: 'עמותות',
    Icon: VolunteerActivismIcon,
    namePrefix: '',
    nameFieldLabel: 'שם העמותה *',
    namePlaceholder: 'לדוגמה: חסדי העיר',
    slugPlaceholder: 'amuta/hasde-david',
    aboutLabel: 'כמה מילים על העמותה',
    aboutPlaceholder: 'ספרו בקצרה על המטרה, הפעילות והערך שהעמותה יוצרת',
    heroTitle: 'צור אתר לעמותה שלך',
    registerTitle: 'צור אתר לעמותה שלך',
    ctaDescription: 'תרומות, פרויקטים, פעילות, שקיפות, מתנדבים ויצירת קשר.',
    defaultSubtitle: 'עשייה, נתינה והשפעה',
    defaultName: 'עמותה',
    pages: {
      schedule: {
        title: 'לוח פעילות ואירועים',
        emptyText: 'לא הוזנו פעילויות עדיין',
        adminTitle: 'לוח פעילות',
        sectionPlaceholder: 'לדוגמה: חלוקה שבועית / אירועים / פעילות מתנדבים',
        rowLabel: 'שם הפעילות',
        rowPlaceholder: 'לדוגמה: חלוקת סלי מזון',
        saveLabel: 'שמור לוח פעילות',
        savedMessage: 'לוח הפעילות עודכן בהצלחה',
        pdfTitle: 'לוח פעילות ואירועים',
        defaultSections: [
          { title: 'פעילות קבועה', rows: [
            { label: 'חלוקת סלי מזון', time: '18:00' },
            { label: 'מוקד סיוע טלפוני', time: '10:00' },
          ] },
          { title: 'אירועים קרובים', rows: [
            { label: 'יום התרמה קהילתי', time: '20:00' },
            { label: 'מפגש מתנדבים', time: '19:30' },
          ] },
        ],
      },
      announcements: {
        title: 'פעילות ועדכונים',
        emptyText: 'אין עדכונים כרגע',
        addTitle: 'הוסף עדכון חדש',
        activeTitle: 'עדכונים פעילים',
        publishLabel: 'פרסם עדכון',
        pinnedLabel: 'הצמד עדכון לראש הרשימה',
      },
      content: {
        title: 'פרויקטים לתרומה',
        subtitle: 'בחרו פרויקט ותהיו שותפים לעשייה',
        description: 'בחרו פרויקט מהרשימה, שלמו באמצעי הנוח לכם ואשרו את התרומה לצוות העמותה',
        adminTitle: 'הוספה ועריכה של פרויקטים',
        activeTitle: 'פרויקטים פעילים',
        itemNameLabel: 'שם הפרויקט',
        itemDescriptionLabel: 'תיאור הפרויקט',
        addLabel: 'הוסף פרויקט',
        saveLabel: 'שמור פרויקט',
        specialCtaTitle: 'רוצים לתרום למטרה אחרת?',
        specialCtaText: 'פנו לצוות העמותה ונשמח לכוון את התרומה למקום המתאים',
      },
      payments: {
        title: 'תרומות ותשלומים',
        subtitle: 'בחרו את אמצעי התרומה הנוח לכם',
        bankDescription: 'העברה ישירה לחשבון העמותה',
        standingOrderDescription: 'הגדירו תרומה חודשית קבועה לתמיכה בפעילות',
        accountCtaTitle: 'רוצים לראות את מצב התרומות שלכם?',
        accountCtaText: 'התחברו עם Google וצפו בחיובים או בתרומות המשויכות אליכם',
        accountButton: 'לאזור האישי שלי',
        standingOrderNote: 'יש למלא ולהחזיר לצוות העמותה',
      },
      campaigns: {
        title: 'קמפיינים',
        subtitle: 'הקימו קמפיין התרמה עם שגרירים, יעדים ולינקים אישיים',
        emptyText: 'אין קמפיינים פעילים כרגע',
        donateLabel: 'תרומה לקמפיין',
        shareLabel: 'שיתוף קישור',
        raiserTitle: 'שגרירים ומתרימים',
        raisedLabel: 'נאסף',
        goalLabel: 'יעד',
        matchedLabel: 'לאחר הכפלה',
      },
      contact: {
        subtitle: 'אנחנו כאן לתרומות, התנדבות ושיתופי פעולה',
        formTitle: 'שלחו פנייה',
        mapTitle: 'מפת פעילות העמותה',
        whatsappTitle: 'הצטרפו לקבוצת העדכונים',
        whatsappText: 'קבלו עדכונים על פעילות, פרויקטים והזדמנויות להתנדבות',
        subjects: ['שאלה כללית', 'תרומה', 'התנדבות', 'שיתוף פעולה', 'פרויקט חדש', 'אחר'],
      },
      admin: {
        loginSubtitle: 'ניהול עמותה',
        settings: 'פרטי העמותה',
        schedule: 'לוח פעילות',
        charges: 'חיובים ותרומות',
      },
    },
    nav: [
      { label: 'ראשי', path: '' },
      { label: 'פעילות', path: 'hodaot' },
      { label: 'פרויקטים', path: 'brachot' },
      { label: 'תרומות', path: 'tashlumim' },
      { label: 'קמפיינים', path: 'campaigns' },
      { label: 'גלריה', path: 'galeria' },
      { label: 'יצירת קשר', path: 'contact' },
      { label: 'ניהול', path: 'admin', adminLink: true },
    ],
    ticker: [
      { cat: 'לתרומה', text: 'שותפים לפרויקט החסד החודשי' },
      { cat: 'להצלחה', text: 'להצלחת כל המתנדבים והתורמים' },
      { cat: 'לעשייה טובה', text: 'ממשיכים להרחיב את מעגל הנתינה' },
    ],
    templateName: 'עמותה',
  },
  yeshiva: {
    id: 'yeshiva',
    label: 'ישיבה',
    pluralLabel: 'ישיבות',
    Icon: SchoolIcon,
    namePrefix: 'ישיבת',
    nameFieldLabel: 'שם הישיבה *',
    namePlaceholder: 'לדוגמה: אור התורה',
    slugPlaceholder: 'yeshiva/or-hatora',
    aboutLabel: 'כמה מילים על הישיבה',
    aboutPlaceholder: 'ספרו בקצרה על בית המדרש, הצוות, הלימוד והאווירה',
    heroTitle: 'צור אתר לישיבה שלך',
    registerTitle: 'צור אתר לישיבה שלך',
    ctaDescription: 'שיעורים, סדרי לימוד, הרשמה, תרומות, הודעות וגלריה.',
    defaultSubtitle: 'תורה, לימוד וצמיחה',
    defaultName: 'ישיבה',
    pages: {
      schedule: {
        title: 'סדרי לימוד ושיעורים',
        emptyText: 'לא הוזנו סדרי לימוד עדיין',
        adminTitle: 'סדרי לימוד',
        sectionPlaceholder: 'לדוגמה: סדר בוקר / סדר צהריים / שיעורים כלליים',
        rowLabel: 'שם הסדר או השיעור',
        rowPlaceholder: 'לדוגמה: סדר א׳ / שיעור כללי',
        saveLabel: 'שמור סדרי לימוד',
        savedMessage: 'סדרי הלימוד עודכנו בהצלחה',
        pdfTitle: 'סדרי לימוד ושיעורים',
        defaultSections: [
          { title: 'סדרי היום', rows: [
            { label: 'סדר בוקר', time: '09:30' },
            { label: 'סדר צהריים', time: '15:30' },
            { label: 'סדר ערב', time: '20:00' },
          ] },
          { title: 'שיעורים כלליים', rows: [
            { label: 'שיעור כללי', time: '12:00' },
            { label: 'שיחת מוסר', time: '19:15' },
          ] },
        ],
      },
      announcements: {
        title: 'הודעות הישיבה',
        emptyText: 'אין הודעות כרגע',
        addTitle: 'הוסף הודעה חדשה',
        activeTitle: 'הודעות פעילות',
        publishLabel: 'פרסם הודעה',
        pinnedLabel: 'הצמד הודעה לראש הרשימה',
      },
      content: {
        title: 'שיעורים ותכניות',
        subtitle: 'שיעורים, סדרים ותכניות לימוד',
        description: 'בחרו שיעור או תכנית מהרשימה, שלמו במידת הצורך ואשרו מול הנהלת הישיבה',
        adminTitle: 'הוספה ועריכה של שיעורים',
        activeTitle: 'שיעורים פעילים',
        itemNameLabel: 'שם השיעור או התכנית',
        itemDescriptionLabel: 'תיאור',
        addLabel: 'הוסף שיעור',
        saveLabel: 'שמור שיעור',
        specialCtaTitle: 'רוצים לברר על שיעור או מסלול נוסף?',
        specialCtaText: 'פנו להנהלת הישיבה ונשמח לעזור',
      },
      payments: {
        title: 'תרומות ותשלומים',
        subtitle: 'בחרו את האמצעי הנוח לכם',
        bankDescription: 'העברה ישירה לחשבון הישיבה',
        standingOrderDescription: 'הגדירו תמיכה חודשית קבועה להחזקת התורה',
        accountCtaTitle: 'רוצים לראות את החשבון שלכם?',
        accountCtaText: 'התחברו עם Google וצפו בחיובים או בתשלומים שלכם',
        accountButton: 'לאזור האישי שלי',
        standingOrderNote: 'יש למלא ולהחזיר להנהלת הישיבה',
      },
      campaigns: {
        title: 'קמפיינים',
        subtitle: 'קמפיין תמיכה עם מתרימים, יעדים ולינקים אישיים',
        emptyText: 'אין קמפיינים פעילים כרגע',
        donateLabel: 'תרומה לקמפיין',
        shareLabel: 'שיתוף קישור',
        raiserTitle: 'מתרימים',
        raisedLabel: 'נאסף',
        goalLabel: 'יעד',
        matchedLabel: 'לאחר הכפלה',
      },
      contact: {
        subtitle: 'אנחנו כאן לשאלות על לימוד, הרשמה ותרומות',
        formTitle: 'שלחו פנייה',
        mapTitle: 'מפת הישיבה',
        whatsappTitle: 'הצטרפו לקבוצת העדכונים',
        whatsappText: 'קבלו עדכונים על שיעורים, סדרים ופעילות הישיבה',
        subjects: ['שאלה כללית', 'הרשמה', 'תרומה', 'שיעורים', 'אירוע בישיבה', 'אחר'],
      },
      admin: {
        loginSubtitle: 'ניהול ישיבה',
        settings: 'פרטי הישיבה',
        schedule: 'סדרי לימוד',
        charges: 'חיובים ותשלומים',
      },
    },
    nav: [
      { label: 'ראשי', path: '' },
      { label: 'סדרי לימוד', path: 'zmanim' },
      { label: 'הודעות', path: 'hodaot' },
      { label: 'שיעורים', path: 'brachot' },
      { label: 'תרומות', path: 'tashlumim' },
      { label: 'קמפיינים', path: 'campaigns' },
      { label: 'גלריה', path: 'galeria' },
      { label: 'יצירת קשר', path: 'contact' },
      { label: 'ניהול', path: 'admin', adminLink: true },
    ],
    ticker: [
      { cat: 'לזכות הלומדים', text: 'להצלחת בני הישיבה בלימודם' },
      { cat: 'לרפואה שלמה', text: 'לרפואת כל חולי ישראל' },
      { cat: 'להחזקת תורה', text: 'שותפים בהמשך קול התורה' },
    ],
    templateName: 'ישיבה',
  },
  organization: {
    id: 'organization',
    label: 'ארגון',
    pluralLabel: 'ארגונים',
    Icon: BusinessIcon,
    namePrefix: '',
    nameFieldLabel: 'שם הארגון *',
    namePlaceholder: 'לדוגמה: מרכז קהילתי הדר',
    slugPlaceholder: 'organization/hadar-center',
    aboutLabel: 'כמה מילים על הארגון',
    aboutPlaceholder: 'ספרו בקצרה על השירותים, הפעילות והקהילה שלכם',
    heroTitle: 'צור אתר לארגון שלך',
    registerTitle: 'צור אתר לארגון שלך',
    ctaDescription: 'שירותים, פעילות, חדשות, תשלומים, גלריה ויצירת קשר.',
    defaultSubtitle: 'פעילות, שירות וקהילה',
    defaultName: 'ארגון',
    pages: {
      schedule: {
        title: 'לוח פעילות ושירותים',
        emptyText: 'לא הוזנו פעילויות עדיין',
        adminTitle: 'לוח פעילות',
        sectionPlaceholder: 'לדוגמה: פעילות שבועית / שירותים / אירועים',
        rowLabel: 'שם הפעילות או השירות',
        rowPlaceholder: 'לדוגמה: מפגש קהילה',
        saveLabel: 'שמור לוח פעילות',
        savedMessage: 'לוח הפעילות עודכן בהצלחה',
        pdfTitle: 'לוח פעילות ושירותים',
        defaultSections: [
          { title: 'פעילות שבועית', rows: [
            { label: 'קבלת קהל', time: '09:00' },
            { label: 'פעילות קהילה', time: '18:30' },
          ] },
          { title: 'שירותים', rows: [
            { label: 'ייעוץ ותיאום פגישה', time: '11:00' },
            { label: 'מפגש צוות', time: '16:00' },
          ] },
        ],
      },
      announcements: {
        title: 'חדשות ועדכונים',
        emptyText: 'אין עדכונים כרגע',
        addTitle: 'הוסף עדכון חדש',
        activeTitle: 'עדכונים פעילים',
        publishLabel: 'פרסם עדכון',
        pinnedLabel: 'הצמד עדכון לראש הרשימה',
      },
      content: {
        title: 'שירותים ופעילויות',
        subtitle: 'כל השירותים והפעילויות במקום אחד',
        description: 'בחרו שירות או פעילות מהרשימה, השלימו תשלום במידת הצורך ופנו לצוות להמשך טיפול',
        adminTitle: 'הוספה ועריכה של שירותים',
        activeTitle: 'שירותים פעילים',
        itemNameLabel: 'שם השירות או הפעילות',
        itemDescriptionLabel: 'תיאור',
        addLabel: 'הוסף שירות',
        saveLabel: 'שמור שירות',
        specialCtaTitle: 'מחפשים שירות שלא מופיע ברשימה?',
        specialCtaText: 'פנו אלינו ונשמח לכוון אתכם',
      },
      payments: {
        title: 'תשלומים',
        subtitle: 'בחרו את אמצעי התשלום הנוח לכם',
        bankDescription: 'העברה ישירה לחשבון הארגון',
        standingOrderDescription: 'הגדירו תשלום חודשי קבוע',
        accountCtaTitle: 'רוצים לראות את החשבון שלכם?',
        accountCtaText: 'התחברו עם Google וצפו בחיובים או בתשלומים שלכם',
        accountButton: 'לאזור האישי שלי',
        standingOrderNote: 'יש למלא ולהחזיר לצוות הארגון',
      },
      campaigns: {
        title: 'קמפיינים',
        subtitle: 'קמפיין גיוס כספים עם צוותים, יעדים ולינקים אישיים',
        emptyText: 'אין קמפיינים פעילים כרגע',
        donateLabel: 'תמיכה בקמפיין',
        shareLabel: 'שיתוף קישור',
        raiserTitle: 'שגרירים ומתרימים',
        raisedLabel: 'נאסף',
        goalLabel: 'יעד',
        matchedLabel: 'לאחר הכפלה',
      },
      contact: {
        subtitle: 'אנחנו כאן לכל שאלה, שירות או שיתוף פעולה',
        formTitle: 'שלחו פנייה',
        mapTitle: 'מפת הארגון',
        whatsappTitle: 'הצטרפו לקבוצת העדכונים',
        whatsappText: 'קבלו עדכונים על פעילות, שירותים וחדשות הארגון',
        subjects: ['שאלה כללית', 'שירותים', 'תשלום', 'שיתוף פעולה', 'פעילות', 'אחר'],
      },
      admin: {
        loginSubtitle: 'ניהול ארגון',
        settings: 'פרטי הארגון',
        schedule: 'לוח פעילות',
        charges: 'חיובים ותשלומים',
      },
    },
    nav: [
      { label: 'ראשי', path: '' },
      { label: 'פעילות', path: 'hodaot' },
      { label: 'שירותים', path: 'brachot' },
      { label: 'תשלומים', path: 'tashlumim' },
      { label: 'קמפיינים', path: 'campaigns' },
      { label: 'גלריה', path: 'galeria' },
      { label: 'יצירת קשר', path: 'contact' },
      { label: 'ניהול', path: 'admin', adminLink: true },
    ],
    ticker: [
      { cat: 'עדכון', text: 'פעילות חדשה נפתחה לקהל הרחב' },
      { cat: 'קהילה', text: 'מצטרפים למעגל העשייה המקומי' },
      { cat: 'שירות', text: 'כל המידע והשירותים במקום אחד' },
    ],
    templateName: 'ארגון',
  },
};

export const SITE_TYPE_OPTIONS = Object.values(SITE_TYPES);

export function getSiteTypeConfig(siteType) {
  return SITE_TYPES[siteType] || SITE_TYPES[DEFAULT_SITE_TYPE];
}
